# Generated by Django 2.2.5 on 2021-05-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_auto_20210505_1518'),
        ('lists', '0002_auto_20210505_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='rooms',
        ),
        migrations.AddField(
            model_name='list',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='lists', to='rooms.Room'),
        ),
    ]
